import type { Metadata } from "next";
import "./globals.css";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import localFont from "next/font/local";
import { QueryProvider } from "@/provider/reactQueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { GlobalErrorHandler } from "@/provider/globalErrorHandlerProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/provider/themeProvider";
const vazir = localFont({
  display: "swap",
  src: [
    { path: "../fonts/Vazir-Light-FD-WOL.woff2", weight: "300" },
    { path: "../fonts/Vazir-FD-WOL.woff2", weight: "400" },
    { path: "../fonts/Vazir-Medium-FD-WOL.woff2", weight: "500" },
    { path: "../fonts/Vazir-Bold-FD-WOL.woff2", weight: "700" },
  ],
});

const inter = localFont({
  display: "swap",
  src: [
    { path: "../fonts/Inter-Light.woff2", weight: "300" },
    { path: "../fonts/Inter-Regular.woff2", weight: "400" },
    { path: "../fonts/Inter-Medium.woff2", weight: "500" },
    { path: "../fonts/Inter-Bold.woff2", weight: "700" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function getDirection(locale: string) {
  return locale === "fa" ? "rtl" : "ltr";
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();
  const font = locale === "fa" ? vazir.className : inter.className;
  return (
    <html lang={locale} dir={getDirection(locale)} suppressHydrationWarning>
      <body className={font}>
        <ThemeProvider
          attribute="class"
          enableSystem={true}
        >
          <NextIntlClientProvider locale={locale} messages={messages}>
            <QueryProvider>
              <TooltipProvider>{children}</TooltipProvider>
              <Toaster className={font} />
              <GlobalErrorHandler />
            </QueryProvider>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
